#!/bin/sh

alias ls="ls -h --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ip="ip -color=auto"
alias du="du -h"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias bc="bc -ql"
alias mkdir="mkdir -pv"
alias wget="wget --no-hsts"

alias sudo="doas"
alias vim="nvim"
alias sxiv="nsxiv"

#PS1='\[\033[00m\][\[\033[1;32m\]\u@\h \[\033[1;34m\]\W\[\033[00m\]]\$ '

for cmd in mount umount fdisk updatedb poweroff reboot; do
	alias $cmd="doas $cmd"
done; unset cmd

ranger() {
	if [ -z "$RANGER_LEVEL" ]; then
		/usr/bin/ranger "$@"
	else
		exit
	fi
}
