#!/bin/sh

export XDG_CONFIG_HOME="$HOME/.config"    
export XDG_DATA_HOME="$HOME/.local/share"    
export XDG_CACHE_HOME="$HOME/.cache"    

export ENV="$XDG_CONFIG_HOME/ash/ashrc"
export PATH="$HOME/.local/bin:$PATH"
export HISTFILE="$XDG_DATA_HOME/history"
export HISTSIZE="1000"

export VISUAL="nvim"

export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
	exec startx $XINITRC
fi
