#!/bin/bash

alias ls="ls -h --color=auto --group-directories-first"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ip="ip -color=auto"
alias du="du -h"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias bc="bc -ql"
alias mkdir="mkdir -pv"
alias wget="wget --no-hsts"
alias gc='git commit'
alias gd='git diff'
alias gp='git push'
alias gst='git status'
alias ga='git add'
alias gco='git checkout'
alias gb='git branch'
alias gl='git log --oneline --graph --decorate'

PS1='\w $ '

for cmd in mount umount fdisk updatedb poweroff reboot; do
	alias $cmd="doas $cmd"
done; unset cmd

alias pys="source .venv/bin/activate"

ranger() {
	if [ -z "$RANGER_LEVEL" ]; then
		/usr/bin/ranger "$@"
	else
		exit
	fi
}
