#!/bin/bash

export XDG_CONFIG_HOME="$HOME/.config"    
export XDG_DATA_HOME="$HOME/.local/share"    
export XDG_CACHE_HOME="$HOME/.cache"    

export PATH="$HOME/.local/bin:$PATH"
export HISTSIZE="1000"

export VISUAL="nvim"

export PYGMENTIZE_STYLE="gruvbox-dark"

export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
	exec startx $XINITRC
fi
