#!/bin/bash

export XDG_CONFIG_HOME="$HOME/.config"    
export XDG_DATA_HOME="$HOME/.local/share"    
export XDG_CACHE_HOME="$HOME/.cache"    

export PATH="$HOME/.local/bin:$PATH"
export HISTSIZE="1000"
export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"

export VISUAL="nvim"

export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"

export PYGMENTIZE_STYLE="gruvbox-dark"

source /etc/profile.d/texlive.sh

if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
	exec startxfce4
fi
